### PR TITLE
Implementation of 5k-9K support

### LINKED ISSUE #16: add the abitty to convert charts with more keys into to osu!mania
i cant convert god eater into osu!mania

make so you can convert fnf charts with more than 4 keys

also add so both sides can be converted into the amount of keys the chart uses for each sid

### PR DESCRIPTION
**Pull request by zzahkaboom24**
Implementation of 5k-9k support based on @Marcos875433's fork over at https://github.com/Marcos875433/fnf2osumania.

Closes #16 

Example images:

image
image
image

### CODE REVIEW

**Comment by zzahkaboom24** [comment]
Its safe to get through now. Got a little confused between his fork, this Repo and the differences between the 2. If there's anything, let me know, I guess

**Review by zzahkaboom24 — COMMENTED** [review]
1.1.8* not 1.1.7

**Comment by Corne2Plum3** [comment]
I didn't checked at the moment as I'm currently unavailable but imo as you add a feature I would more name the version 1.2.0 instead of 1.1.8.

**Comment by zzahkaboom24** [comment]
Sure. I have to continue testing it anyways, cuz I am not sure about some parts of it

**Comment by Corne2Plum3** [comment]
I checked your code before you set it as a draft and I don't see any issues.

Anyways if you want, once you're done with it comment below so I merge your work.

**Comment by zzahkaboom24** [comment]
Check again, I reimplemented your Note removal/ignoring with extra arguments

**Comment by Corne2Plum3** [comment]
I don't have any issue with it, I gonna merge it then.

**Comment by Corne2Plum3** [comment]
Thanks you btw

**Pull request merged**
