### PR TITLE
Fix crash, when trying to convert maps that have more than 3 arguments

### PR DESCRIPTION
**Pull request by zzahkaboom24**
Issue #7 which I randomly stumbled by. I am unsure wether my small bug fix is okay or not, but it seems to have worked for me. And as I dont have much time today, its the best I could do rq.

(I did try it with the same song and map from the issue and it worked, and a version bump is not necessary, since it was solved in version 1.1.2, so its safe to merge, and simply update the release file)

### CODE REVIEW

**Comment by Corne2Plum3** [comment]
Would be good if you could tell which version you used and which map you tried, so I can recreate the bug and better understand the bug...

**Comment by zzahkaboom24** [comment]
@Corne2Plum3 Sure. I used the latest version from the releases (1.2.0) and I used the following 3 files (2 for sound, 1 for data)

[screwed-hard.json](https://github.com/Corne2Plum3/fnf2osumania/files/12921121/screwed-hard.json)

[inst+voices.zip](https://github.com/Corne2Plum3/fnf2osumania/files/12921125/inst%2Bvoices.zip)

**Comment by Corne2Plum3** [comment]
I got this

```
Traceback (most recent call last):
  File "C:\Users\corne\Desktop\fnf2osumania\fnf_converter.py", line 849, in exportAsOsz
    osu_map.fnf_charts[k].exportOsuFile(self.folder_path, k, osu_map.creator, osu_map.tags)
  File "C:\Users\corne\Desktop\fnf2osumania\fnf_converter.py", line 214, in exportOsuFile
    notes_list.sort()  # sort the notes by offset order (using the index 0)
    ^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by zzahkaboom24** [comment]
yes, i got that too. my pr should technically fix it

**Comment by Corne2Plum3** [comment]
Your fix does works, however in `note_list` you may have a 4th argument, which shouldn't be here, but it seems to be ignored by the rest of the program, so I'm okay with it.

image

Anyways I believe this also happens because the functions `getNotesPlayer` let this unused information.

Also I think having an unique function which takes an additional parameter: the amount of keys instead of a single function for each key count would be very nice. I'll probably try to work on that when i'll have time in the next days.

**Comment by Corne2Plum3** [comment]
btw I'm not going to add this to releases right now in case you find other bugs, and also i'll try to work on the code, thing that I didn't do for more than 1 year lol

**Comment by zzahkaboom24** [comment]
understandable. Ill keep looking into it once in a while to see if I catch something. I can't really forget about this project cuz it's the only one really capable of converting fnf to osu properly and easily (thanks for this btw)

**Pull request merged**
